spring:
  kafka:
    bootstrap-servers: localhost:9092
  datasource:
    password: 1234
    username: msproject
    url: jdbc:postgresql://localhost:5555/
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8001



